---
title: "LeBron James"
author: "Nuray Nasib & Aymir Aydinli"
date: "6/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# LeBron James

LeBron James, (born Dec. 30, 1984, Akron, Ohio, U.S.), U.S. basketball player. A basketball prodigy, he was the consensus national high-school player of the year in 2003. He subsequently was selected first overall by the Cleveland Cavaliers in the 2003 NBA draft. James quickly established himself as one of the league’s dominant players. He was named Rookie of the Year in 2004 and later won multiple Most Valuable Player awards (2009, 2010, 2012, and 2013). After the 2009–10 season he signed with the Miami Heat, and he helped the franchise win championships in 2012 and 2013. He returned to the Cavaliers in 2014 and guided the team to its first NBA title in 2016. Two years later he joined the Los Angeles Lakers and helped them capture the championship in 2020. James also was a member of the U.S. Olympic basketball teams that won the bronze medal in 2004 and gold medals in 2008 and 2012.


